# Generated by Django 6.0.3 on 2026-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
