# Generated by Django 6.0.3 on 2026-03-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vendorprofile_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
