# Generated by Django 6.0.3 on 2026-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vendorprofile_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
